language: c

sudo: required

services:
- docker

before_script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

script:
- make build
- '[ "$TRAVIS_PULL_REQUEST" = false ] && make push || true'

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: evszvN4g/0Q3XojkyUvSE3AB+/JhWVFNZG4aeYauiQ0UXp9OMATipCtX3FQPAl52EX4X9+iu9Ia6NNwsgUWu8mq0Ccptgb6xB1qGgxg+NScuBYcLzRIszVhEdyVsPA5ETPBeB2SN/WHQ1AETnmYPjtwpw6XMlwFwt0OyE4g4n+zr5+kbBse4HUzoQum/DLYR4BBYrCjQYs1bXITg9Ojmq4Dgt2v21jHOeoZGQEFQ97bZvUEAEjbRafSP2OsjP7lAmKP3v3EBLQ4kdaAuOYKcssxylRwaDHy3y/vYUPZaV7aeY8kfFacbndykH35nktyFe0tujGhgep/G/JWm9elIBwj45kTaPeTD4r/5MhFPukh/SzCzkJ+H+WcLQTD6dvBzYzWBAjYoA8qAG0XmSxv3gg+7oZyZTAoi1DIKTXsBMjCWCZEU97NqvpYQzqHOOVfROw9z5UFCraWU8uZ5Fin0BKpzyf90n4HG7YaZc9pCk+gSromjjOduDmEo0sjfbo3F9YISvNG2dsonEE17OLkrI3yUepAI2zx22fl8ZZKhYjkc/CDwTGMhaTJOOG71hT6x5To63uQx2c2Qmr+glFkIqK8Ma2cPEDg0w+37FpqDO36rkDjGxSAhJgqzGXyaaSeeA9WaUatQwJP/MtJgxyEDlV9iQvjbwfCRyDf3pGuQj9M=
  - secure: JAYN6euW1Dz5tvH7UVjw5+x3h1MT1NWbhv3n60aTNNNQHv7cb1O0S2oEfWumv+DVEPP2KHLaADYlAsYGlKWdS0xkd/XtcScJO/Ipn/uX3R4AjWrAurYomt8UH4+BQqm2ADpGDr1LOGf10JdpHgP+bUhF+aXWHgfup66hHdgLNRVdH7L/8BUfHcRK3CPeJ5AzImG+k+XKCFqlAfbr7TqjbLGZqSuU517xD7Sh2O7PK1a1spMXcgz1RTFUa0EpAHUXEUvhXvY+zaafFvcx3Zlfm7Qk1vsXNiXsw//AES3rIWlHtQ1qwn0ojlQMQibvGA4nxTB9OC2G6Zura4ejIdFCYCyzgxDome1L30m5Gp4vLTAO0tdlLxhxHGfZ5ZgpHbjgZ+zvsV53jRnRFdT17VQEBsooSOH+3L6jJ3Q8Um7gESkX/wlnSwiF6yacT9ioQWWSquGgov7x4UPpWQBM2jm4upgyj6hkpI6J4Prc9TZnBChuZ7YYXqJEsk0jaiEb9valeaGxtcYENwo5YRWB+69t6Icl1Vqg2mvXq2FF/RLvu5uJH2qukHklyUjQq9Fg3UslbMhBDFgxAlokfywCmyzR/y9Z+LJdOG6YDkZjF5p5b6ex2Nj4ESirdNHVRmytBVqn77MX/JiLmgys3GJPPuNYte1+XR5783wV5rgRMRmd0nU=

notifications:
  slack:
    secure: QKhBN/xrud201HaQpHZ/bhWDc2EJo3CLpKuNyKLg1oo8x6QUz2BBBtDJ4C9h6EULpQNhvtXxwpy4x4E3VDA7t+Ko25ANDNFfRdxTZEeRni+j43gvmV/dN96zueE/z+eJIfyqNR7dhmIvYcZdtOzihD4mrFW1pfGxmTybAnw1V5dPdSObNzWMyBpFXMJo2DQ+Mo/KY6oI4jr9YZGKkWQgb/hWIeo7NpBoM7XGNpw5r5tfwrKGOemQabafpeG7qHrhJP204nG4e7UJNPtVGqWO9dR0ArAOgrSB9oYekgc0sIbMiH2ELZFCnb1T3pnYcS6w5w3AbbMzzYY/IrbLjTYsz8/MvzdKEGzxH8oTvlYMaCJBNXa/HqNJDlP3PILwjPehNa1rIsdG2mp0Ien2fJ9dcefWSXmIyHi6t4Nq0DHh7asXzllvBd3Z329bux6iCrZPVaOnnXXRMnfnXdtZz6RM4w6q0iBkBmG5wSCjWyEsu+CrpDHFhs2eLd81JBTNTn3/0fjhWcKxlkBYmJ+0TTx3J9H/z3ZRnH/X3dobdAkcmrUCGz/363fvRLOA2cDO51QxQYUkPQpDEnhjfM8bN82Od8mWxk4iK9kKD61Tkmd6Cu/U/2P23t9adPxOL3JxYVg6kGSj2oNF6+3AUW0j6WhnRVwRW9mGrE1PJThzvsVaZ5g=
